### ISSUE TITLE
Unable to install the astrowand project (and other tinyml projects) locally and run it

### ISSUE THREAD

**Issue by We-Jay** [googlecreativelab/astrowand#1]
I have been trying to run the code for Astrowand locally, but have been unsuccessful so for.

I understand that it has been built using Svelte. So I am basically doing the following:

Download the code. Go into the **astrowand/web** directory and then running **nmp install**. 

But this step is yielding many errors and I cannot proceed to **npm run dev.**

I also ran **yarn install**  and I am getting similar issues.  (Both the screenshots included)

<img width="688" alt="Screenshot 2021-06-30 at 1 45 39 PM" src="https://user-images.githubusercontent.com/34061747/123939634-f1903580-d9b5-11eb-83a0-4f21a93c62e9.png">
<img width="682" alt="Screenshot 2021-06-30 at 1 48 28 PM" src="https://user-images.githubusercontent.com/34061747/123939646-f654e980-d9b5-11eb-9b21-19d2fffaa99e.png">

I am stuck. Is there any **instruction** that will help us run this code locally so that we can experiment further? Thanks in advance.

**Comment by rikard-io** [comment]
@We-Jay  should be working now. Just run npm / yarn install again, no need to clone / download this repo again.

**Comment by rikard-io** [comment]
@We-Jay actually, might have spoken too early. Yarn still seem to throw some issues. Was able to get around it by running `yarn add -D https://github.com/googlecreativelab/tf4micro-motion-kit` before `yarn install` but will look into it further.

**Comment by rikard-io** [comment]
if you do a fresh clone / download and run yarn install it should work now.

**Comment by We-Jay** [comment]
I first tried with **npm install**, and am still facing the same error issues.

When I tried, **yarn install**, it compiled without any issues.

And then I used **npm run dev** and it runs nicely.
Alternatively, I used **npm start**, and it runs like a charm.

Thanks a lot, Rikard for looking into it.

**Comment by rikard-io** [comment]
Glad you got it to work! Thank you for reporting.

Fixed npm issue here: https://github.com/googlecreativelab/tf4micro-motion-kit/pull/7 

Closing ticket
